DELETE FROM "COCKPITSCHEMA"."CCM_ER_EOB_REGISTRY";
DELETE FROM "COCKPITSCHEMA"."CCM_JR_JOB_REGISTRY";
DELETE FROM "COCKPITSCHEMA"."CCM_MA_MESSAGE_ADDRESS";
DELETE FROM "COCKPITSCHEMA"."CCM_MP_MESSAGE_PPOD";
DELETE FROM "COCKPITSCHEMA"."CCM_MR_MESSAGE_REGISTRY";
DELETE FROM "COCKPITSCHEMA"."CCM_RM_RESOURCE_MAP";
DELETE FROM "COCKPITSCHEMA"."CCM_TR_TICKET_REGISTRY";
DELETE FROM "COCKPITSCHEMA"."CCM_OUT_MESSAGES";

DELETE FROM "COCKPITSCHEMA"."ERRORINFO";
DELETE FROM "COCKPITSCHEMA"."ERRORREF";
DELETE FROM "COCKPITSCHEMA"."JOBINFO";
DELETE FROM "COCKPITSCHEMA"."POSTPROCINDATA";
DELETE FROM "COCKPITSCHEMA"."POSTPROCOUTDATA";

DELETE FROM "COCKPITSCHEMA"."PPE_ENVELOPE";
DELETE FROM "COCKPITSCHEMA"."PPE_EXECUTION";
DELETE FROM "COCKPITSCHEMA"."PPE_PPOD";
DELETE FROM "COCKPITSCHEMA"."PPE_PPOD_ENV";
DELETE FROM "COCKPITSCHEMA"."PPE_METADATA_SEGMENT_1";
DELETE FROM "COCKPITSCHEMA"."PPE_METADATA_SEGMENT_2";
DELETE FROM "COCKPITSCHEMA"."PPE_METADATA_SEGMENT_3";
DELETE FROM "COCKPITSCHEMA"."PPE_METADATA_SEGMENT_4";
DELETE FROM "COCKPITSCHEMA"."PPE_METADATA_SEGMENT_5";
DELETE FROM "COCKPITSCHEMA"."PPE_METADATA";

